// tests/rules.test.mjs — end-to-end tests for the Rules ops over the real HTTP
// route: dispatch through the handlers table, WRITE_OPS token gating, and the
// on-disk effect of rules-create / rules-toggle (always layer).
//
// The pure rule-store logic (discovery / derivation / CRUD / index / trash /
// scenes) is covered by tests/rules-service.test.mjs against lib/rules/service.js;
// this file exercises the wiring in lib/index.js.
import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, existsSync, readFileSync, rmSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import plugin from '../lib/index.js'

// Fake Cordis ctx (same shape as mcpm.test.mjs): webServer.register captures the
// route; ctx.on captures the tools/pre-execute hook for the approval tests.
function makeCtx(home) {
  let route = null
  const listeners = new Map()
  const files = new Map()
  const ctx = {
    timer: {},
    timeout: () => Promise.resolve(),
    settings: { prepareDocument: async () => join(home, 'settings.yaml') },
    sandboxPolicy: { resolve: async () => ({}) },
    tools: { register() {}, schemas: () => [], guard() { return () => {} }, restrict() { return () => {} } },
    webServer: { register(r) { route = r; return () => {} } },
    fs: {
      async resolve(p) { return p },
      async stat(p) { return undefined },
      async readText(p) { const e = new Error('not found'); e.code = 'FS_NOT_FOUND'; throw e },
      async writeText() {},
      async listDir() { return [] },
    },
    effect(fn) { const d = fn(); if (typeof d === 'function') d() },
    on(ev, cb) { listeners.set(ev, cb) },
    events: { dispatch: () => [] },
    get() { return undefined },
    skills: { registerProvider() {}, async snapshot() { return { skills: [], complete: true } }, async get() { return undefined } },
    _route: () => route,
    _listeners: listeners,
    _files: files,
  }
  return ctx
}

function call(route, payload, headers = {}) {
  const b = JSON.stringify(payload)
  const req = {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-dsh-plugin': 'dsh-plugin-tool-management', ...headers },
    on(ev, cb) { if (ev === 'data') cb(b); if (ev === 'end') cb() },
  }
  const res = { status: 200, bodyText: '', writeHead(c) { this.status = c }, end(b2) { this.bodyText = b2 || '' } }
  const p = route.handler(req, res)
  return (p ? Promise.resolve(p) : Promise.resolve()).then(() => ({ status: res.status, json: res.bodyText ? JSON.parse(res.bodyText) : null }))
}

const temp = () => {
  const home = mkdtempSync(join(tmpdir(), 'dsh-rules-e2e-'))
  return {
    home,
    rulesRoot: join(home, 'rules'),
    stateDir: join(home, 'tool-management'),
    agentsMd: join(home, 'AGENTS.md'),
    cleanup: () => rmSync(home, { recursive: true, force: true }),
  }
}

test('rules: create via route writes a flat file; list reads it back with form field', async () => {
  const t = temp()
  try {
    const ctx = makeCtx(t.home)
    plugin.apply(ctx, { rulesRoot: t.rulesRoot, rulesStateDir: t.stateDir })
    let r = await call(ctx._route(), { op: 'rules-create', args: { group: 'office', name: 'doc-writing', description: '文档写作约定', body: '正文第一行\n正文第二行' } })
    assert.equal(r.json.ok, true)
    assert.equal(r.json.rule.id, 'office/doc-writing')
    assert.equal(r.json.rule.form, 'flat')
    const file = join(t.rulesRoot, 'office', 'doc-writing.md')
    assert.ok(existsSync(file), 'rule file written to disk')
    assert.match(readFileSync(file, 'utf8'), /^---\nname: doc-writing\ndescription: 文档写作约定\n---\n正文第一行\n正文第二行/)
    r = await call(ctx._route(), { op: 'rules-list', args: {} })
    assert.equal(r.json.ok, true)
    assert.equal(r.json.rules.length, 1)
    assert.equal(r.json.rules[0].form, 'flat')
    assert.equal(r.json.rules[0].enabled, true)
    assert.equal(r.json.stats.total, 1)
  } finally { t.cleanup() }
})

test('rules: toggle always:true compiles into the global AGENTS.md', async () => {
  const t = temp()
  try {
    const ctx = makeCtx(t.home)
    // getGlobalAgentsMdPath in index.ts resolves DSH_HOME; point it at the temp home.
    const prev = process.env.DSH_HOME
    process.env.DSH_HOME = t.home
    try {
      plugin.apply(ctx, { rulesRoot: t.rulesRoot, rulesStateDir: t.stateDir })
      let r = await call(ctx._route(), { op: 'rules-create', args: { group: '_shared', name: 'glossary', description: '术语表', body: '每页都要遵守' } })
      assert.equal(r.json.ok, true)
      r = await call(ctx._route(), { op: 'rules-toggle', args: { id: '_shared/glossary', always: true } })
      assert.equal(r.json.ok, true)
      assert.equal(r.json.rule.always, true)
      const agents = readFileSync(t.agentsMd, 'utf8')
      assert.match(agents, /<!-- generated by dsh-plugin-tool-management; do not edit by hand -->/)
      assert.match(agents, /## 术语表/)
      assert.match(agents, /每页都要遵守/)
    } finally {
      if (prev === undefined) delete process.env.DSH_HOME
      else process.env.DSH_HOME = prev
    }
  } finally { t.cleanup() }
})

test('rules: WRITE_OPS token gate blocks writes without token, allows reads', async () => {
  const t = temp()
  try {
    const ctx = makeCtx(t.home)
    plugin.apply(ctx, { token: 'secret-123', rulesRoot: t.rulesRoot, rulesStateDir: t.stateDir })
    // 写无 token → 拒绝
    let r = await call(ctx._route(), { op: 'rules-create', args: { group: 'g', name: 'a', description: 'd', body: 'b' } })
    assert.equal(r.json.ok, false)
    assert.match(r.json.error, /令牌/)
    // 写带正确 token → 成功
    r = await call(ctx._route(), { op: 'rules-create', args: { group: 'g', name: 'a', description: 'd', body: 'b' } }, { 'x-dsh-token': 'secret-123' })
    assert.equal(r.json.ok, true)
    // 读不需要 token
    r = await call(ctx._route(), { op: 'rules-list', args: {} })
    assert.equal(r.json.ok, true)
    assert.equal(r.json.rules.length, 1)
  } finally { t.cleanup() }
})

test('rules: hand-written flat rule with derived fields is listed', async () => {
  const t = temp()
  try {
    mkdirSync(join(t.rulesRoot, '_shared'), { recursive: true })
    writeFileSync(join(t.rulesRoot, '_shared', 'no-fm.md'), '# 无 frontmatter 规则\n\n正文', 'utf8')
    const ctx = makeCtx(t.home)
    plugin.apply(ctx, { rulesRoot: t.rulesRoot, rulesStateDir: t.stateDir })
    const r = await call(ctx._route(), { op: 'rules-list', args: {} })
    assert.equal(r.json.ok, true)
    const rule = r.json.rules.find((x) => x.id === '_shared/no-fm')
    assert.ok(rule, 'derived rule listed')
    assert.equal(rule.name, 'no-fm')
    assert.equal(rule.description, '无 frontmatter 规则')
    assert.equal(rule.descriptionDerived, true)
  } finally { t.cleanup() }
})
