// dsh-plugin-tool-management —— 规则「始终层」投影（编译进 ~/.dsh/AGENTS.md）。
//
// 与 AGENTS.md 预设库（agents-md）的区别：agents-md 是整文件覆盖切换预设，
// 这里是把 always:true && enabled:true 的规则**确定性拼接**成一段，以「段替换」
// 的方式合入全局 AGENTS.md —— 只替换本插件生成的段，保留用户其他内容。
//
// 为什么不用整文件覆盖：AGENTS.md 是 DSH 的全局指令基线，用户可能手写内容
// 或安装其他预设；整文件覆盖会静默销毁它们。段替换只动我们自己的段落。
//
// 确定性红线：段内容只由规则（group → order → name 排序）决定，禁止时间戳/
// 计数/相对时间 —— 否则每次写文件都会产生 diff，测试与版本控制都无法收敛。
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
export const ALWAYS_MARKER = '<!-- generated by dsh-plugin-tool-management; do not edit by hand -->';
export const DEFAULT_MAX_BYTES = 65536;
/** 确定性排序：group → order → name（与 rules-list 排序一致）。 */
export function compareAlways(a, b) {
    return (a.group.localeCompare(b.group) ||
        a.order - b.order ||
        a.name.localeCompare(b.name));
}
/** 单条规则段：`## <description 或 name>` + 空行 + 正文（尾部单个换行）。 */
export function compileOne(e) {
    return `## ${e.description || e.name}\n\n${String(e.body ?? '').trim()}\n`;
}
/** 编译整段（marker 行 + 各规则段）。纯函数：相同输入恒等输出，字节数可复算。
 *  无 always 规则时返回空段 —— 避免向 AGENTS.md 写入空 marker 噪音。 */
export function compileAlwaysProjection(entries) {
    const sorted = [...entries].sort(compareAlways);
    if (!sorted.length)
        return { text: '', bytes: 0 };
    const text = ALWAYS_MARKER + '\n\n' + sorted.map(compileOne).join('\n');
    return { text, bytes: Buffer.byteLength(text, 'utf8') };
}
/**
 * 段替换：把 section 合入既有 AGENTS.md 内容。
 * - 已存在本插件 marker → 替换「marker 到其后第一个 H1（`# `）标题」之间的内容；
 *   我们的段全部是 H2（`## `），用户新起的大章节用 H1 自然分隔。找不到 H1 时
 *   段延伸到文件末尾（我们生成的段总是追加在末尾，覆盖最常见场景）。
 * - 不存在 marker → 追加到末尾（空文件直接写入）。
 */
export function applyAlwaysSection(content, section) {
    const src = String(content ?? '');
    const idx = src.indexOf(ALWAYS_MARKER);
    if (idx < 0) {
        if (src === '')
            return { content: section, replaced: false };
        const sep = src.endsWith('\n') ? '' : '\n';
        return { content: src + sep + '\n' + section, replaced: false };
    }
    let end = src.length;
    const h1 = src.indexOf('\n# ', idx + ALWAYS_MARKER.length);
    if (h1 >= 0)
        end = h1;
    const before = src.slice(0, idx);
    const after = src.slice(end);
    const sep = before === '' || before.endsWith('\n') ? '' : '\n';
    return { content: before + sep + section + after, replaced: true };
}
/** 同目录临时文件 + rename 的原子写（临时名带本插件前缀，避免与技能域混淆）。 */
async function writeFileAtomically(path, content) {
    const temp = join(dirname(path), `.${basename(path)}.dsh-rules-${randomUUID()}.tmp`);
    try {
        await writeFile(temp, content, 'utf8');
        await rename(temp, path);
    }
    catch (error) {
        await rm(temp, { force: true }).catch(() => undefined);
        throw error;
    }
}
/**
 * 写始终层投影。写入前先做预算检查（本插件段总字节 ≤ maxBytes），超限**拒绝写入**
 * 并返回 error.rules.budgetExceeded —— 不写文件，避免把 AGENTS.md 撑爆。
 * 内容未变化（幂等重投影）时不触碰文件。
 */
export async function writeAlwaysProjection(getGlobalAgentsMdPath, entries, maxBytes) {
    const { text, bytes } = compileAlwaysProjection(entries);
    const max = Number.isFinite(maxBytes) && maxBytes > 0 ? maxBytes : DEFAULT_MAX_BYTES;
    if (bytes === 0)
        return { ok: true, replaced: false, bytes: 0 }; // 无 always 规则：不触碰 AGENTS.md
    if (bytes > max) {
        return {
            ok: false,
            error: `始终层超出预算（${bytes} 字节 > ${max} 字节），已拒绝写入`,
            code: 'error.rules.budgetExceeded',
        };
    }
    const globalPath = await getGlobalAgentsMdPath();
    let content = '';
    try {
        content = await readFile(globalPath, 'utf8');
    }
    catch {
        /* 文件不存在视为空 → 追加 */
    }
    const merged = applyAlwaysSection(content, text);
    if (merged.content !== content) {
        await mkdir(dirname(globalPath), { recursive: true });
        await writeFileAtomically(globalPath, merged.content);
    }
    return { ok: true, replaced: merged.replaced, bytes };
}
